### ISSUE TITLE
[REFACTORING] Заменить Json2oPage на конвертор

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#1]
Класс Json2oPage можно заметить конвертором - имплементировать **Converter<S, T>**

**Comment by li-stas** [comment]
add class Json2Page - поддержка логики приложения
add class Json2PageConverter - конвертер json String -> Page
add WebConfig - для регистрации  конвертера
https://github.com/li-stas/filmpoisk02/commit/4d19f8d93791a3c544bc10d3cbd3e7fa2b61f8e0
