### ISSUE TITLE
[APP] Добавить XML

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#12]
Согласно ТЗ, необходимо добавить в проект возможность получать данные в формате XML

Один из вариантов [описан тут](https://stackoverflow.com/questions/33009918/spring-boot-controller-content-negotiation/33010537#33010537)

**Comment by li-stas** [comment]
Добавлена возможность.
http://localhost:8080/filmpoisk-id.json?id=tt0119654
http://localhost:8080/filmpoisk-id?id=tt0119654
формат получения json
http://localhost:8080/filmpoisk-id.xml?id=tt0119654
формат получения .xml
за основу взят пример от сюда https://www.javainuse.com/spring/spring-boot-content-negotiation

Реализовано только в этом контроллере (filmpoisk-id).
