### ISSUE TITLE
[REFACTORING] Переименовать пакеты и перенести классы

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#14]
Необходимо именовать пакеты и классы согласно их функционала.
Пакет **converters** логичнее переименовать в (например) **processors** (или как-то иначе)
Пакет **model.lib -> model.converters**

Перенести класс DownloadImage в **model.converters**

**Comment by li-stas** [comment]
Выполнено. Один из вариантов
https://github.com/li-stas/filmpoisk02/commit/9a9d3ba296099ef9e5299c774cb3c17e30aba734
