### ISSUE TITLE
[REFACTORING] Рефакторинг классов

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#15]
Класс **WordReplaceTextInFormFields** не должен быть запускаемым
Кдасс **LookupId** скорее модель, чем контроллер

**Comment by li-stas** [comment]
Класс WordReplaceTextInFormFields не должен быть запускаемым - закоментирован main
Кдасс LookupId - перенесен

**Comment by anry-das** [comment]
Там бы вообще main убрать
а уж throws Exception так точно не нужен
