### ISSUE TITLE
[MODEL] Алгоритм получения постера

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#16]
Сейчас постер после получения сохраняется в файл, а потом вставляется в документ - это не совсем правильно.
Необходимо это поведение изменить - получать постер в **стрим** и передавать в формирующийся документ.

**Comment by li-stas** [comment]
в классе Page сохраняется стрим. 
run.addPicture(is, XWPFDocument , is - получает значение стрим из поля класса Page
