### ISSUE TITLE
Класс Json2Page не бин

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#17]
Скорее всего класс Json2Page не должен быть бином (сейчас это бин).
Или же его не нужно создавать при помощи new, но тогда нужна будет фабрика для него.

**Comment by li-stas** [comment]
https://github.com/li-stas/filmpoisk02/commit/558e35e894c1016fde60b4edf720769e26ed078c
class Json2Page {
    public Page eval(String cPage, Page oPage, ConversionService conversionService)

передается как параметр conversionService
