### ISSUE TITLE
Параметры запроса в Rest Template

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#18]
Параметры в Rest Template можно формировать / передавать, как описано тут
https://stackoverflow.com/questions/35998790/resttemplate-how-to-send-url-and-query-parameters-together
(без использования String)

**Comment by anry-das** [comment]
это в LookupId

**Comment by li-stas** [comment]
сформировал чз url = builder.buildAndExpand(urlParams).toUri().toString();
передавал тоже чз String тк нужен json
 cPage = restTemplate.getForObject(url, String.class);

https://github.com/li-stas/filmpoisk02/commit/69b2b6a90ca833ea476af8faedeb4a9d77fb0377
