### ISSUE TITLE
[REFACTORING] Изменить алгоритм формирования файла

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#2]
Необходимо изменить алгоритм формирования файла.
Сейчас файл формируется и сохраняется на стороне приложения, а потом отдается по запросу.
Нужно это поведение изменить - формировать файл в стриме и возвращать в ответе на запрос.
Почитать можно тут https://dzone.com/articles/streaming-data-with-spring-boot-restful-web-servic
Также есть несколько примеров тут https://www.programcreek.com/java-api-examples/index.php?api=org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody

**Comment by li-stas** [comment]
изменено.
1. Документ создается и обрабатывается XWPFDocument docx
2. Создан новый @RestController с @RequestMapping("/getdocx02") GetDocxStreamContoller.java
3. Создан  @Component public class GetStream1 в котором для получения InputStreamResource resource используется комбинация      ByteArrayOutputStream out -> ByteArrayInputStream(out.toByteArray())

Пример использования контроллера 
http://localhost:8080/getdocx02?id=tt0118843

https://github.com/li-stas/filmpoisk02/commit/cd0bb5e7a5197f760c70045aaf0e62bd4c5bad72
