### ISSUE TITLE
[REFACTORING] Рефакторинг классов и пакетов

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#22]
Классы GetFile1 и GetStream1 необходимо переименовать - убрать 1.
GetDocxContoller скорее всего не нужен. Поэтому его можно удалить. Вместе с ним можно удалить GetFile1
Кроме того, GetFile1 и GetStream1 - это сервисы и д.б. в соотв. пакете.
MediaTypeUtils - также нужно вынескти к сервисам.

Можно подумать об удалении GreetingController - в приложении он не несет полезной нагрузки.

**Comment by li-stas** [comment]
Рефакторинг - выполнен
https://github.com/li-stas/filmpoisk02/commit/92a2914e2ccb4377e92b71bb562c58bb37fec492
