### ISSUE TITLE
Задержка в LookupId не нежна

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#23]
Задержка в LookupId
**Thread.sleep(10);**
не нужна, т.к. **Future.get()** уже ждет результата (https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html#get())

**Comment by li-stas** [comment]
Future.get() уже ждет результата - ок!, Но можно и не дождаться результата! Поэтому

Задействована задержка Thread.sleep(10);
в конфигурацию введен параметр: 
    1. #время ожидания для одиночных запросов, с
     ini.api.timeoutforsinglerequests=10
  2. LookupId - обработана эта настройка
https://github.com/li-stas/filmpoisk02/commit/850d6ea575433077165825924fc39a3a472c4823
