### ISSUE TITLE
Формирование URL в RestTemplates

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#24]
В LookupId URL формируется с помощью конкантенации, но это можно сделать по другому - с помощью UriComponentsBuilder и карты параметров
(описано тут https://stackoverflow.com/questions/35998790/resttemplate-how-to-send-url-and-query-parameters-together)

**Comment by li-stas** [comment]
конструирование запроса с помощью UriComponentsBuilder реализовано в OmDbApiLookupService. Для это в качестве  первого параметра      findPage()
 нужно передать пустую строку.
Режим формирования запроса с помощью конкантенации отключен в LookupId. Путем использования условной компиляции.
http://www.javapractices.com/topic/TopicAction.do?Id=64

https://github.com/li-stas/filmpoisk02/commit/01a1d7f758d535e9e352add1d4d906280dd1238d
