### ISSUE TITLE
Финальный рефакторинг

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#30]
**DownloadImage**
 - перенести в пакет services
 - сделать сервисом
 - удалить DownloadImage из Page.setPoster
 - перенести вызов DownloadImage в контроллер (с использованием DI)
 - выделить из класса интерфейс и использоватье его при DI

**Json2Page и Json2oPage**
 - рассмотреть целесообразность использования
 - удалить, заменив на Json2PageConverter
 
**Json2PageConverter**
 - функционал метода extractFromMapPage поместить в convert
 
**LookupId**
 - сделать сервисом
 - использовать в контроллере с помощью DI
 - выделить из класса интерфейс и использоватье его при DI
 
**MediaTypeUtils** - используется только в одном месте:
 - рассмотреть возможность перенести функционал в GetDocxStream или
 - рассмотреть возможность сделать компонентом и использовать с помощью DI
 
**WordWorker**
 - удалить, т.к. не используется

**Comment by li-stas** [comment]
без LookupId
https://github.com/li-stas/filmpoisk02/commit/2647d25e2cafe1b54ff5b982943cbb0168d16b56
LookupId
https://github.com/li-stas/filmpoisk02/commit/44afb747e43f0b02d4ad7a35e0a54b4460e035ff

**Comment by li-stas** [comment]
Json2Page - удален
https://github.com/li-stas/filmpoisk02/commit/a33261006593ece2021fe7304666a031e92a2766

**Comment by anry-das** [comment]
вот это еще не сделано:

- "выделить из класса интерфейс и использоватье его при DI"

для DownloadImage и LookupId
можно их переименовать в DownloadImageImpl и LookupIdImpl
и добавить инт-сы DownloadImage и LookupId

- у Json2PageConverter добавь аннотацию Component

- FilmPoiskIdContoller используй DI для LookupId

Пока вроде все

**Comment by li-stas** [comment]
переделано и вытекающие из этого всего последствия.(удалены new для вызова методов функционала)
https://github.com/li-stas/filmpoisk02/commit/4220035152652dcd44b47a23b964b32986399c05

**Comment by anry-das** [comment]
GetDocxStream:
- переименовать в GetDocxStreamImpl
- выделить интерфейс GetDocxStream и использовать его в DI

**Comment by li-stas** [comment]
Добрый. …!

  
>Понедельник, 10 февраля 2020, 10:06 +02:00 от Andrey Denysenko <notifications@github.com>:
> 
>GetDocxStream:
>*  переименовать в GetDocxStreamImpl
>*  выделить интерфейс GetDocxStream и использовать его в DI
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
============
Стас

**Comment by li-stas** [comment]
Добрый. день!
По этой проблеме создана 
 
*  issue   #33    переименовать в GetDocxStreamImpl 
*  сделаны изменения в исходном коде.
*  issue  33 закрыта.
    
>Понедельник, 10 февраля 2020, 10:06 +02:00 от Andrey Denysenko <notifications@github.com>:
> 
>GetDocxStream:
>*  переименовать в GetDocxStreamImpl
>*  выделить интерфейс GetDocxStream и использовать его в DI
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
============
Стас
