### ISSUE TITLE
[CODE] Замена конкатенации на StringBuilder

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#4]
Необходимо заменить конкатенации (например cUrl01 = "?apikey=" + config.getApikey() + "&i=" + cSeekId;) на использование **StringBuilder / StringBuffer**

**Comment by li-stas** [comment]
Замена конкатенации на StringBuilder
и такой вариант преобразования (MessageFormat.format)
public String toString() {
        return MessageFormat.format("Querying'{'id={0}, content=''{1}'''}'", id, content);
    }
