### ISSUE TITLE
[LOGGING] Использовать привильное логгирование ошибок

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#5]
В таких случаях
`log.error(e.getMessage() + " InterruptedException");`
необходимо также добавлять вывож стектрейса:
`log.error(e.getMessage() + " InterruptedException", e);`

**Comment by li-stas** [comment]
исправлено. Добавлен стек вызов.
https://github.com/li-stas/filmpoisk02/commit/733826a9d33499b332bec153ca1f1fb3fd38c684
