### ISSUE TITLE
[REFACTORING] Повторяющийся код

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#7]
В **WordWorker** и **WordRepl** повторяющийся код можно вынести в отдельный метод

**Comment by li-stas** [comment]
оптимизирован код WordWorker
https://github.com/li-stas/filmpoisk02/commit/3462f62f948bb672df82b07926b197bd92bc7a2e

**Comment by li-stas** [comment]
class WordRepl метод eval - удален и разделен на два метода saveToFile getXWPFDocument
см 
https://github.com/li-stas/filmpoisk02/commit/cd0bb5e7a5197f760c70045aaf0e62bd4c5bad72
