### ISSUE TITLE
[CODE] Упростить код

### ISSUE THREAD

**Issue by anry-das** [li-stas/filmpoisk02#8]
Такой оператор if
```
if (ffname.equals(((SimpleValue)obj).getStringValue())) {
     = true;
} else {
    foundformfield = false;
}
```
можно упростить:
`foundformfield = ffname.equals(((SimpleValue)obj).getStringValue());`

**Comment by li-stas** [comment]
Код упрощен
https://github.com/li-stas/filmpoisk02/commit/72d2c4fdda261692d73a217879b837f8f0b9ac43
